"""Emit the .features.step.js manifest sidecar the viewer's legend panel reads."""
from __future__ import annotations

import json
from pathlib import Path

from featurekit.model import Part


def _payload(part: Part, *, step_path: str) -> dict:
    return {
        "manifest": {
            "schemaVersion": 1,
            "step": {"path": step_path},
            "features": part.manifest(),
        },
        "view": {"colorMode": "diagnostic", "ghostCutters": True},
    }


def render_sidecar(part: Part, *, step_path: str) -> str:
    data = _payload(part, step_path=step_path)
    blob = json.dumps(data, indent=2)
    # Embed a machine-readable JSON block (for tooling/tests) plus the live ES export.
    return (
        "// Generated by featurekit. Do not edit by hand.\n"
        "/*FEATUREKIT_JSON\n" + blob + "\nFEATUREKIT_JSON*/\n"
        "export default " + blob + ";\n"
    )


def _repo_relative_posix(path: Path) -> str:
    resolved = path.resolve()
    # Walk up looking for the repo root (a .git dir); fall back to the file name.
    for parent in [resolved, *resolved.parents]:
        if (parent / ".git").exists():
            try:
                return resolved.relative_to(parent).as_posix()
            except ValueError:
                break
    return resolved.name


def write_sidecar(part: Part, *, features_step_path: Path) -> Path:
    features_step_path = Path(features_step_path)
    step_rel = _repo_relative_posix(features_step_path)
    js = render_sidecar(part, step_path=step_rel)
    out = features_step_path.with_suffix(features_step_path.suffix + ".js")
    out.write_text(js, encoding="utf-8")
    return out
